---
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################         Jobs below are used to build only             #########################################
#######################                  master  branches                     #########################################
#######################                 for all containers                    #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

# 1/2 This pipeline would be used after each merge request  to build ml_all:latest docker image
kind: pipeline
type: docker
name: mmsegmentaion LS_mmdeploy_latest

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - main
  event:
    - push

node:
  docker: build_only

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

clone:
  depth: 1

steps:
  - name: Build latest mmsegmentation LS_mmdeploy docker image
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      AWS_ACCESS_KEY_ID:
        from_secret: DRONE_CI_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DRONE_CI_AWS_SECRET_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings: 
      dockerfile: deploy_docker/Dockerfile
      context: deploy_docker/
      registry: quay.io
      repo: quay.io/logivations/mmsegmentation
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      cache_from: quay.io/logivations/mmsegmentation:LS_mmdeploy_latest
      tags:
        - LS_mmdeploy_latest
        - LS_mmdeploy_latest_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD

  - name: Build latest mmsegmentation LS_mmseg docker image
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      AWS_ACCESS_KEY_ID:
        from_secret: DRONE_CI_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DRONE_CI_AWS_SECRET_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      dockerfile: docker/Dockerfile
      context: docker/
      registry: quay.io
      repo: quay.io/logivations/mmsegmentation
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      cache_from: quay.io/logivations/mmsegmentation:LS_mmseg_latest
      tags:
        - LS_mmseg_latest
        - LS_mmseg_latest_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################              Jobs below are used to run               #########################################
#######################             pull request validation only              #########################################
#######################                                                       #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

---
## 1. Pre-commit validation before start docker build
# kind: pipeline
# type: docker
# name: PR validation pre-commit check

# platform:
#   arch: amd64
#   os: linux

# clone:
#   disable: true

# trigger:
#   event:
#     include:
#       - pull_request

# image_pull_secrets:
#   - dockerconfig_prd

# steps:
#   - name: Pre-commit validation
#     image: 
#     pull: always
#     commands:
#       - git clone --depth 1 ${DRONE_GIT_HTTP_URL} -b ${DRONE_SOURCE_BRANCH}
#       - cd mmsegmentation && git fetch --depth 1 origin ${DRONE_TARGET_BRANCH} && git diff --name-only FETCH_HEAD | xargs pre-commit run --files


# 2. Build docker image for mmsegmentation
---
kind: pipeline
type: docker
name: PR validation build mmsegmentation images

platform:
  arch: arm64
  os: linux

trigger:
  event:
    include:
      - pull_request

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

# depends_on:
#   - PR validation pre-commit check

clone: 
  depth: 50

steps:
  - name: Build mmsegmentation LS_mmdeploy docker image for pull request
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      AWS_ACCESS_KEY_ID:
        from_secret: DRONE_CI_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DRONE_CI_AWS_SECRET_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings: 
      dockerfile: deploy_docker/Dockerfile
      context: deploy_docker/
      registry: quay.io
      repo: quay.io/logivations/mmsegmentation
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      cache_from: 
        - quay.io/logivations/mmsegmentation:LS_mmdeploy_latest
        - quay.io/logivations/mmsegmentation:LS_mmdeploy_pr${DRONE_PULL_REQUEST}
      tags:
        - LS_mmdeploy_pr${DRONE_PULL_REQUEST}
        - LS_mmdeploy_pr${DRONE_PULL_REQUEST}_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD

  - name: Build mmsegmentation LS_mmseg docker image for pull request
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
      AWS_ACCESS_KEY_ID:
        from_secret: DRONE_CI_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DRONE_CI_AWS_SECRET_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings: 
      dockerfile: docker/Dockerfile
      context: docker/
      registry: quay.io
      repo: quay.io/logivations/mmsegmentation
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      build_args_from_env:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      cache_from: 
        - quay.io/logivations/mmsegmentation:LS_mmseg_latest
        - quay.io/logivations/mmsegmentation:LS_mmseg_pr${DRONE_PULL_REQUEST}
      tags:
        - LS_mmseg_pr${DRONE_PULL_REQUEST}
        - LS_mmseg_pr${DRONE_PULL_REQUEST}_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD
---
