variables:
  PARROTS_IMAGE: registry.sensetime.com/platform/product:pat0.6.0rc0
  PYTORCH_IMAGE: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
    - linting
    - test
    - deploy

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

.linting_template: &linting_template_def
  stage: linting
  script:
    - pip install flake8 yapf isort
    - flake8 .
    - isort -rc --check-only --diff mmseg/ tools/ tests/
    - yapf -r -d mmseg/ tools/ tests/ configs

.test_template: &test_template_def
  stage: test
  script:
    - echo "Start building..."
    - export MMCV_CUDA_ARGS="-gencode=arch=compute_61,code=sm_61"
    - pip install "git+https://github.com/open-mmlab/mmcv.git"
    - pip install -e .[all]
    - python -c "import mmseg; print(mmseg.__version__)"
    - echo "Start testing..."
    - coverage run --branch --source mmseg -m pytest tests/
    - coverage report -m --omit="mmseg/utils/*","mmseg/apis/*","mmseg/datasets/samplers/*"

linting:pytorch1.3-cuda10:
  image: $PYTORCH_IMAGE
  <<: *linting_template_def

linting:pat0.6.0dev-cuda9:
  image: $PARROTS_IMAGE
  <<: *linting_template_def

test:pytorch1.3-cuda10:
  image: $PYTORCH_IMAGE
  <<: *test_template_def

# test:pat0.6.0dev-cuda9:
#   image: $PARROTS_IMAGE
#   <<: *test_template_def

pages:
  image: $PYTORCH_IMAGE
  stage: deploy
  script:
    - pip install sphinx sphinx_rtd_theme recommonmark
    - cd docs
    - make html
    - cd ..
    - mkdir -p ./public
    - cp -r docs/_build/html/* ./public
    - ls ./public
  artifacts:
    paths:
      - public
  only:
    - master
