Models:
- Name: upernet_beit_base_12_640_slide_160k_ade20k_pt2ft
  In Collection: UperNet
  Metadata:
    backbone: BEiT-B
    crop size: (640,640)
    lr schd: 160000
    inference time (ms/im):
    - value: 500.0
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (640,640)
    Training Memory (GB): 16.27
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 53.08
      mIoU(ms+flip): 53.84
  Config: configs/beit/upernet_beit_base_12_640_slide_160k_ade20k_pt2ft.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/beit/upernet_beit_base_12_640_slide_160k_ade20k_pt2ft/upernet_beit_base_12_640_slide_160k_ade20k_pt2ft_upernet_beit_base_12_640_slide_160k_ade20k_pt2f-eead221d.pth
- Name: upernet_beit_large_fp16_24_640_slide_160k_ade20k_pt2ft
  In Collection: UperNet
  Metadata:
    backbone: BEiT-L
    crop size: (640,640)
    lr schd: 320000
    inference time (ms/im):
    - value: 1041.67
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP16
      resolution: (640,640)
    Training Memory (GB): 23.18
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 56.33
      mIoU(ms+flip): 56.84
  Config: configs/beit/upernet_beit_large_fp16_24_640_slide_160k_ade20k_pt2ft.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/beit/upernet_beit_large_fp16_24_640_slide_160k_ade20k_pt2ft/upernet_beit_large_fp16_24_640_slide_160k_ade20k_pt2ft_upernet_beit_large_fp16_24_640_slide_160k_ade20k_pt2f-8fc0dd5d.pth
