Collections:
- Name: PIDNet
  Metadata:
    Training Data:
    - Cityscapes
  Paper:
    URL: https://arxiv.org/pdf/2206.02066.pdf
    Title: 'PIDNet: A Real-time Semantic Segmentation Network Inspired from PID Controller'
  README: configs/pidnet/README.md
  Code:
    URL: https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/backbones/pidnet.py
    Version: dev-1.x
  Converted From:
    Code: https://github.com/XuJiacong/PIDNet
Models:
- Name: pidnet-s_2xb6-120k_1024x1024-cityscapes
  In Collection: PIDNet
  Metadata:
    backbone: PIDNet-S
    crop size: (1024,1024)
    lr schd: 120000
    inference time (ms/im):
    - value: 12.37
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (1024,1024)
    Training Memory (GB): 3.38
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.74
      mIoU(ms+flip): 80.87
  Config: configs/pidnet/pidnet-s_2xb6-120k_1024x1024-cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/pidnet/pidnet-s_2xb6-120k_1024x1024-cityscapes/pidnet-s_2xb6-120k_1024x1024-cityscapes_20230302_191700-bb8e3bcc.pth
- Name: pidnet-m_2xb6-120k_1024x1024-cityscapes
  In Collection: PIDNet
  Metadata:
    backbone: PIDNet-M
    crop size: (1024,1024)
    lr schd: 120000
    inference time (ms/im):
    - value: 13.89
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (1024,1024)
    Training Memory (GB): 5.14
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.22
      mIoU(ms+flip): 82.05
  Config: configs/pidnet/pidnet-m_2xb6-120k_1024x1024-cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/pidnet/pidnet-m_2xb6-120k_1024x1024-cityscapes/pidnet-m_2xb6-120k_1024x1024-cityscapes_20230301_143452-f9bcdbf3.pth
- Name: pidnet-l_2xb6-120k_1024x1024-cityscapes
  In Collection: PIDNet
  Metadata:
    backbone: PIDNet-L
    crop size: (1024,1024)
    lr schd: 120000
    inference time (ms/im):
    - value: 16.65
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (1024,1024)
    Training Memory (GB): 5.83
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.89
      mIoU(ms+flip): 82.37
  Config: configs/pidnet/pidnet-l_2xb6-120k_1024x1024-cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/pidnet/pidnet-l_2xb6-120k_1024x1024-cityscapes/pidnet-l_2xb6-120k_1024x1024-cityscapes_20230303_114514-0783ca6b.pth
