Collections:
- Metadata:
    Training Data:
    - Cityscapes
  Name: bisenetv1
Models:
- Config: configs/bisenetv1/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-18-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 31.48
    lr schd: 160000
    memory (GB): 5.69
  Name: bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 74.44
      mIoU(ms+flip): 77.05
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/bisenetv1/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes_20210922_172239-c55e78e2.pth
- Config: configs/bisenetv1/bisenetv1_r18-d32_in1k-pre_4x4_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-18-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 31.48
    lr schd: 160000
    memory (GB): 5.69
  Name: bisenetv1_r18-d32_in1k-pre_4x4_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 74.37
      mIoU(ms+flip): 76.91
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/bisenetv1/bisenetv1_r18-d32_in1k-pre_4x4_1024x1024_160k_cityscapes/bisenetv1_r18-d32_in1k-pre_4x4_1024x1024_160k_cityscapes_20210905_220251-8ba80eff.pth
- Config: configs/bisenetv1/bisenetv1_r18-d32_in1k-pre_4x8_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-18-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 31.48
    lr schd: 160000
    memory (GB): 11.17
  Name: bisenetv1_r18-d32_in1k-pre_4x8_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 75.16
      mIoU(ms+flip): 77.24
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/bisenetv1/bisenetv1_r18-d32_in1k-pre_4x8_1024x1024_160k_cityscapes/bisenetv1_r18-d32_in1k-pre_4x8_1024x1024_160k_cityscapes_20210905_220322-bb8db75f.pth
- Config: configs/bisenetv1/bisenetv1_r50-d32_4x4_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-50-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 129.7
    lr schd: 160000
    memory (GB): 3.3
  Name: bisenetv1_r50-d32_4x4_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.92
      mIoU(ms+flip): 78.87
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/bisenetv1/bisenetv1_r50-d32_4x4_1024x1024_160k_cityscapes/bisenetv1_r50-d32_4x4_1024x1024_160k_cityscapes_20210923_222639-7b28a2a6.pth
- Config: configs/bisenetv1/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-50-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 129.7
    lr schd: 160000
    memory (GB): 15.39
  Name: bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 77.68
      mIoU(ms+flip): 79.57
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/bisenetv1/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes/bisenetv1_r50-d32_in1k-pre_4x4_1024x1024_160k_cityscapes_20210917_234628-8b304447.pth
