Collections:
- Metadata:
    Training Data:
    - Cityscapes
  Name: bisenetv1
Models:
- Config: configs/bisenetv1/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-18-D32
    crop size: (1024,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (1024,1024)
      value: 31.48
    lr schd: 160000
    memory (GB): 3.3
  Name: bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 74.37
      mIoU(ms+flip): 76.91
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fast_scnn/fast_scnn_lr0.12_8x4_160k_cityscapes/fast_scnn_lr0.12_8x4_160k_cityscapes_20210630_164853-0cec9937.pth
- Config: configs/bisenetv1/bisenetv1_r18-d32_4x8_1024x1024_160k_cityscapes.py
  In Collection: bisenetv1
  Metadata:
    backbone: R-18-D32
    crop size: (1024,1024)
    lr schd: 160000
    memory (GB): 3.3
  Name: bisenetv1_r18-d32_4x8_1024x1024_160k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 75.16
      mIoU(ms+flip): 77.24
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fast_scnn/fast_scnn_lr0.12_8x4_160k_cityscapes/fast_scnn_lr0.12_8x4_160k_cityscapes_20210630_164853-0cec9937.pth
